GENERAL_FONTNAME = "Arial"
GENERAL_FONT_WEIGHT = "bold"
GENERAL_FONT_STYLE = "italic"

POSITIVE_COLOR = "#45EF45"
NEGATIVE_COLOR = "#EE5555"
CHART_INDEX_COLOR = "#ff9900"

COMPONENT_ASSET_FOOTER_TEXT_COLOR = "#555555"
COMPONENT_ASSET_FOOTER_FACE_COLOR = "#f7f7f7"
COMPONENT_ASSET_FOOTER_EDGE_COLOR = "#e0e0e0"

DATE_FORMAT = "%d/%m/%y %I:%M:%S %p"